#! /bin/sh

sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor LVDS-1 -d 1 2 3 4 5 
bspc monitor VGA-1 -d 6 7 8 9 0

bspc config focused_border_color "#D5C4A1"

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle     	 true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' focus=on follow=on
bspc rule -a firefox focus=on follow=on
bspc rule -a Emacs focus=on state=tiled follow=on

# set background image
#feh --bg-fill ~/Storage/Downloads/Wallpapers/wallpaper4.png
feh --bg-fill ~/Storage/Masters/Rice/Polybar/polybar-themes/polybar-12/wallpapers/bg_1.jpg

# start polybar
sh .config/polybar/launch.sh

# start picom
picom &

# run xrandr command if an external monitor is connected
# if [ -x $HOME/.config/bspwm/dualmonitor ];
# then
# 	dualmonitor
# fi
