lowercaseKeywords: false
connections:
  - alias: simple-bank
    driver: postgresql
    proto: tcp
    user: root
    passwd: secret
    host: 127.0.0.1
    port: 5432
    dbName: simple-bank
  - alias: libraryapp
    driver: mssql
    proto: tcp
    user: sa
    passwd: Password1
    host: 127.0.0.1
    port: 1433
    dbName: librarydb
